services:
  load-hive-{{ .HiveID }}-node:
    image: hub.deepin.com/library/locustio/locust:latest
    working_dir: /mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host={{ .MainIP }} --master-port={{ .InternalAPIPort}}
    volumes:
      - './:/mnt/locust/:ro'
{{ if .ExtraHosts }}
    extra_hosts:
{{ range $hostStr := .ExtraHosts }}
      - '{{ $hostStr }}'
{{ end }}
{{ end }}
    restart: always
